# Generated by Django 5.2 on 2025-06-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('study_number', models.CharField(max_length=200)),
                ('study_sponsor', models.CharField(max_length=200)),
                ('study_type', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Draft', max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('study_file', models.FileField(blank=True, null=True, upload_to='study_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='DomainDetectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.domain')),
            ],
            options={
                'verbose_name': 'Domain Detection Prompt',
                'verbose_name_plural': 'Domain Detection Prompts',
            },
        ),
        migrations.CreateModel(
            name='DomainExtractionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.domain')),
            ],
            options={
                'verbose_name': 'Domain Extraction Prompt',
                'verbose_name_plural': 'Domain Extraction Prompts',
            },
        ),
        migrations.CreateModel(
            name='FDAFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='fda_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.study')),
            ],
            options={
                'verbose_name': 'FDA File',
                'verbose_name_plural': 'FDA Files',
            },
        ),
        migrations.CreateModel(
            name='ExtractedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('xpt_file', models.FileField(blank=True, null=True, upload_to='xpt_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.domain')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.study')),
            ],
            options={
                'verbose_name': 'Extracted Domain',
                'verbose_name_plural': 'Extracted Domains',
            },
        ),
        migrations.CreateModel(
            name='DetectedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.JSONField()),
                ('page', models.JSONField()),
                ('confident_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.domain')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.study')),
            ],
            options={
                'verbose_name': 'Deetected Domain',
                'verbose_name_plural': 'Deetected Domains',
            },
        ),
        migrations.CreateModel(
            name='StudyConent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.study')),
            ],
            options={
                'verbose_name': 'Study Content',
                'verbose_name_plural': 'Study Contents',
            },
        ),
    ]
