# Generated by Django 5.2 on 2025-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_documentupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyConent',
            new_name='StudyContent',
        ),
    ]
