# Generated by Django 5.2 on 2025-06-24 11:20

import builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_rename_studyconent_studycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddomain',
            name='xpt_file',
            field=models.FileField(blank=True, null=True, upload_to=builder.models.xpt_file_path),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_file',
            field=models.FileField(blank=True, null=True, upload_to=builder.models.study_file_path),
        ),
    ]
