# Generated by Django 5.2 on 2025-07-23 14:12

import builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_extracteddomain_xpt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddomain',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=builder.models.xpt_file_path),
        ),
    ]
