# Generated by Django 5.2 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect_with_ai', models.BooleanField(default=False)),
                ('extract_with_ai', models.BooleanField(default=False)),
                ('use_smart_cache', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('CHAT', 'Chat Model'), ('EMBEDDING', 'Embedding Model'), ('CODE', 'Code Model')], max_length=20)),
                ('provider', models.CharField(default='ollama', max_length=50)),
                ('model_size', models.CharField(blank=True, help_text='e.g. 7b, 13b, etc.', max_length=50)),
                ('context_length', models.IntegerField(default=4096)),
                ('namespace', models.CharField(blank=True, help_text='deepseek-r1, llama-2, etc.', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0.1)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
            },
        ),
    ]
